name: Cypress Tests 

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Fixed unsupported Ubuntu version
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install  # Ensures Cypress and dependencies are installed

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true  # Runs tests without opening UI